export { default as PendingApproval } from './PendingApproval';
//export { default as LatestOrders } from './LatestOrders';
//export { default as LatestProducts } from './LatestProducts';
export { default as LatestSales } from './LatestSales';
export { default as TasksProgress } from './PendingAllocation';
export { default as ClosedThisMonth } from './ClosedThisMonth';
export { default as PendingShipment } from './PendingShipment';
export { default as UsersByDevice } from './UsersByDevice';
export { default as PendingAllocation } from './PendingAllocation';